In [15]:
#Arithmetic 1D Array
import numpy as np
arr = np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [20]:
arr[0:-1]+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [21]:
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       , 0.09090909, 0.08333333, 0.07692308, 0.07142857,
       0.06666667, 0.0625    , 0.05882353, 0.05555556, 0.05263158])

In [22]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [34]:
#Arithmetic 2D Array
arr_2d = [[1,2,3],[5,6,7],[9,10,11]]
x = np.array(arr_2d)
x.shape

(3, 3)

In [40]:
x.reshape(3,3)

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [41]:
x**2

array([[  1,   4,   9],
       [ 25,  36,  49],
       [ 81, 100, 121]])

In [42]:
arr_1d = np.array([1,2,3])
arr_2d * arr_1d

array([[ 1,  4,  9],
       [ 5, 12, 21],
       [ 9, 20, 33]])

In [46]:
x / arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])

In [48]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [50]:
np.sin(x)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.41211849, -0.54402111, -0.99999021]])

In [51]:
np.log(x)

array([[0.        , 0.69314718, 1.09861229],
       [1.60943791, 1.79175947, 1.94591015],
       [2.19722458, 2.30258509, 2.39789527]])

In [55]:
np.insert(arr_1d,3,3)

array([1, 2, 3, 3])

In [56]:
arr_1d

array([1, 2, 3])

In [58]:
x

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [60]:
np.insert(x, 3,3)

array([ 1,  2,  3,  3,  5,  6,  7,  9, 10, 11])

In [61]:
a = np.array([[1,2],[4,5]])
b = np.array([[5,7]])
np.concatenate((a,b),axis=0)

array([[1, 2],
       [4, 5],
       [5, 7]])

In [62]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [4, 5, 7]])

In [63]:
np.concatenate((a,b),axis = None)

array([1, 2, 4, 5, 5, 7])

In [64]:
np.where(arr>6,1,arr)

array([0, 1, 2, 3, 4, 5, 6, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [65]:
np.where(arr>5,1,2)

array([2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [66]:
np.where(x <=3,0,x)

array([[ 0,  0,  0],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [ ]:
#Pandas

In [69]:
import numpy as np
import pandas as pd
labels = ['a','b','c']
my_list = [1,2,3]
arr = np.array([10,20,30])
d = {'a':10, 'b':20, 'c':30}
pd.Series(data = my_list)

0    1
1    2
2    3
dtype: int64

In [71]:
pd.Series(data = my_list, index = labels)

a    1
b    2
c    3
dtype: int64

In [72]:
pd.Series(my_list, labels)

a    1
b    2
c    3
dtype: int64

In [73]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [74]:
pd.Series(arr,labels)

a    10
b    20
c    30
dtype: int64

In [75]:
d = {'a':10, 'b':20, 'c':30}
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [80]:
a = [i for i in range(1,5)]
b = [i for i in range(5,9)]
c = [i for i in range(9,13)]

In [81]:
pd.DataFrame(data=[a,b,c])

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [82]:
pd.DataFrame([a,b,c], 'x y z'.split(), 'e f g h'.split())

e   f   g   h
x  1   2   3   4
y  5   6   7   8
z  9  10  11  12

In [83]:
pd.DataFrame(data=[a,b,c],
             index='a b c'.split(),
             columns = 'w x y z'.split())

w   x   y   z
a  1   2   3   4
b  5   6   7   8
c  9  10  11  12

In [86]:
pd.DataFrame(data=[a,b,c],
             index='a b c'.split(),
             columns='w x y z'.split()).T

a  b   c
w  1  5   9
x  2  6  10
y  3  7  11
z  4  8  12

In [87]:
from numpy.random import randn
np.random.seed(101)

In [90]:
df = pd.DataFrame(randn(7,3),index='A B C D E F G'.split(),columns='W X Y '.split())
df

W         X         Y
A  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579
C  0.649826  2.154846 -0.610259
D -0.755325 -0.346419  0.147027
E -0.479448  0.558769  1.024810
F -0.925874  1.862864 -1.133817
G  0.610478  0.386030  2.084019

In [96]:
my_d = {'a':[1,2,3,4,5,6],
        'b':[7,8,9,10,11,20],
        'c':[12,13,14,15,16,17]}
pd.DataFrame(my_d,index='h e l l o w'.split())

a   b   c
h  1   7  12
e  2   8  13
l  3   9  14
l  4  10  15
o  5  11  16
w  6  20  17